<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Constants for ClassEngage plugin
 *
 * @package    mod_classengage
 * @copyright  2025 Danielle
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace mod_classengage;

defined('MOODLE_INTERNAL') || die();

/**
 * ClassEngage constants class
 */
class constants
{

    // Session status constants.
    /** @var string Session is ready to start */
    const SESSION_STATUS_READY = 'ready';

    /** @var string Session is currently active */
    const SESSION_STATUS_ACTIVE = 'active';

    /** @var string Session is paused */
    const SESSION_STATUS_PAUSED = 'paused';

    /** @var string Session is completed */
    const SESSION_STATUS_COMPLETED = 'completed';

    // Question status constants.
    /** @var string Question is pending review */
    const QUESTION_STATUS_PENDING = 'pending';

    /** @var string Question is approved for use */
    const QUESTION_STATUS_APPROVED = 'approved';

    /** @var string Question is rejected */
    const QUESTION_STATUS_REJECTED = 'rejected';

    // Question source constants.
    /** @var string Question generated by NLP service */
    const QUESTION_SOURCE_NLP = 'nlp';

    /** @var string Question created manually */
    const QUESTION_SOURCE_MANUAL = 'manual';

    // Question type constants.
    /** @var string Multiple choice question */
    const QUESTION_TYPE_MULTICHOICE = 'multichoice';

    /** @var string True/false question */
    const QUESTION_TYPE_TRUEFALSE = 'truefalse';

    /** @var string Short answer question */
    const QUESTION_TYPE_SHORTANSWER = 'shortanswer';

    // Answer options.
    /** @var array Valid answer options for multiple choice */
    const VALID_ANSWERS = ['A', 'B', 'C', 'D'];

    // Slide status constants.
    /** @var string Slide has been uploaded */
    const SLIDE_STATUS_UPLOADED = 'uploaded';

    /** @var string Slide processing is complete */
    const SLIDE_STATUS_COMPLETED = 'completed';

    /** @var string Slide processing encountered an error */
    const SLIDE_STATUS_ERROR = 'error';

    // Action constants.
    /** @var string Action to advance to next question */
    const ACTION_NEXT = 'next';

    /** @var string Action to stop session */
    const ACTION_STOP = 'stop';

    /** @var string Action to pause session */
    const ACTION_PAUSE = 'pause';

    /** @var string Action to resume session */
    const ACTION_RESUME = 'resume';

    /** @var array Valid control panel actions */
    const VALID_ACTIONS = [
        self::ACTION_NEXT,
        self::ACTION_STOP,
        self::ACTION_PAUSE,
        self::ACTION_RESUME,
    ];

    // Default configuration values.
    /** @var int Default polling interval in milliseconds */
    const DEFAULT_POLLING_INTERVAL = 1000;

    /** @var int Default number of questions per session */
    const DEFAULT_NUM_QUESTIONS = 10;

    /** @var int Default time limit per question in seconds */
    const DEFAULT_TIME_LIMIT = 30;

    // =========================================================================
    // Enterprise Optimization: Rate Limiting Constants
    // =========================================================================

    /** @var int Maximum requests per minute per user */
    const RATE_LIMIT_REQUESTS_PER_MINUTE = 120;

    /** @var int Maximum batch size for response submissions */
    const MAX_BATCH_SIZE = 50;

    /** @var int Maximum concurrent connections per session */
    const MAX_CONNECTIONS_PER_SESSION = 500;

    /** @var int Rate limit window in seconds */
    const RATE_LIMIT_WINDOW = 60;

    // =========================================================================
    // Enterprise Optimization: Connection Management Constants
    // =========================================================================

    /** @var int Connection stale timeout in seconds (consider stale after this) */
    const CONNECTION_STALE_TIMEOUT = 45;

    /** @var int Maximum SSE connection runtime in seconds */
    const MAX_SSE_RUNTIME = 300;

    /** @var int Reconnect delay initial value in milliseconds */
    const RECONNECT_DELAY_INITIAL = 1000;

    /** @var int Maximum reconnect delay in milliseconds */
    const RECONNECT_DELAY_MAX = 30000;

    /** @var int Connection timeout in milliseconds */
    const CONNECTION_TIMEOUT = 10000;

    // =========================================================================
    // Enterprise Optimization: Cache TTL Constants (in seconds)
    // =========================================================================

    /** @var int Cache TTL for response statistics */
    const CACHE_TTL_RESPONSE_STATS = 2;

    /** @var int Cache TTL for session state */
    const CACHE_TTL_SESSION_STATE = 60;

    /** @var int Cache TTL for connection status */
    const CACHE_TTL_CONNECTION_STATUS = 10;

    /** @var int Cache TTL for analytics summary */
    const CACHE_TTL_ANALYTICS_SUMMARY = 30;

    /** @var int Cache TTL for question data */
    const CACHE_TTL_QUESTION_DATA = 3600;

    // =========================================================================
    // Enterprise Optimization: Error Codes
    // =========================================================================

    /** @var int Error: Session not found */
    const ERROR_SESSION_NOT_FOUND = 1001;

    /** @var int Error: Session not active */
    const ERROR_SESSION_NOT_ACTIVE = 1002;

    /** @var int Error: Already answered */
    const ERROR_ALREADY_ANSWERED = 1003;

    /** @var int Error: Rate limit exceeded */
    const ERROR_RATE_LIMIT_EXCEEDED = 1004;

    /** @var int Error: Invalid answer format */
    const ERROR_INVALID_ANSWER = 1005;

    /** @var int Error: Connection timeout */
    const ERROR_CONNECTION_TIMEOUT = 1006;

    /** @var int Error: Database error */
    const ERROR_DATABASE = 1007;

    /** @var int Error: Permission denied */
    const ERROR_PERMISSION_DENIED = 1008;

    // =========================================================================
    // Enterprise Optimization: Performance Thresholds
    // =========================================================================

    /** @var float Target response latency in seconds (NFR-01) */
    const TARGET_RESPONSE_LATENCY = 1.0;

    /** @var float Target success rate percentage (NFR-03) */
    const TARGET_SUCCESS_RATE = 95.0;

    /** @var int Target concurrent users per session */
    const TARGET_CONCURRENT_USERS = 200;

    /** @var float Question broadcast target latency in seconds */
    const TARGET_BROADCAST_LATENCY = 0.5;

    // =========================================================================
    // Enterprise Optimization: Event Types for Logging
    // =========================================================================

    /** @var string Event type: Session started */
    const EVENT_SESSION_START = 'session_start';

    /** @var string Event type: Session ended */
    const EVENT_SESSION_END = 'session_end';

    /** @var string Event type: Response submitted */
    const EVENT_RESPONSE = 'response';

    /** @var string Event type: Connection established */
    const EVENT_CONNECTION = 'connection';

    /** @var string Event type: Disconnection */
    const EVENT_DISCONNECTION = 'disconnection';

    /** @var string Event type: Error occurred */
    const EVENT_ERROR = 'error';

    /** @var string Event type: Warning */
    const EVENT_WARNING = 'warning';

    /** @var string Event type: Reconnection */
    const EVENT_RECONNECT = 'reconnect';

    // =========================================================================
    // Enterprise Optimization: Validation Rules
    // =========================================================================

    /** @var int Maximum session name length */
    const MAX_SESSION_NAME_LENGTH = 255;

    /** @var int Maximum question text length */
    const MAX_QUESTION_TEXT_LENGTH = 10000;

    /** @var int Maximum answer length */
    const MAX_ANSWER_LENGTH = 255;

    /** @var int Minimum time limit per question */
    const MIN_TIME_LIMIT = 5;

    /** @var int Maximum time limit per question */
    const MAX_TIME_LIMIT = 600;

    /** @var int Minimum questions per session */
    const MIN_QUESTIONS_PER_SESSION = 1;

    /** @var int Maximum questions per session */
    const MAX_QUESTIONS_PER_SESSION = 100;
}

