<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Constants for ClassEngage plugin
 *
 * @package    mod_classengage
 * @copyright  2025 Your Name
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace mod_classengage;

defined('MOODLE_INTERNAL') || die();

/**
 * ClassEngage constants class
 */
class constants {
    
    // Session status constants.
    /** @var string Session is ready to start */
    const SESSION_STATUS_READY = 'ready';
    
    /** @var string Session is currently active */
    const SESSION_STATUS_ACTIVE = 'active';
    
    /** @var string Session is paused */
    const SESSION_STATUS_PAUSED = 'paused';
    
    /** @var string Session is completed */
    const SESSION_STATUS_COMPLETED = 'completed';
    
    // Question status constants.
    /** @var string Question is pending review */
    const QUESTION_STATUS_PENDING = 'pending';
    
    /** @var string Question is approved for use */
    const QUESTION_STATUS_APPROVED = 'approved';
    
    /** @var string Question is rejected */
    const QUESTION_STATUS_REJECTED = 'rejected';
    
    // Question source constants.
    /** @var string Question generated by NLP service */
    const QUESTION_SOURCE_NLP = 'nlp';
    
    /** @var string Question created manually */
    const QUESTION_SOURCE_MANUAL = 'manual';
    
    // Question type constants.
    /** @var string Multiple choice question */
    const QUESTION_TYPE_MULTICHOICE = 'multichoice';
    
    /** @var string True/false question */
    const QUESTION_TYPE_TRUEFALSE = 'truefalse';
    
    /** @var string Short answer question */
    const QUESTION_TYPE_SHORTANSWER = 'shortanswer';
    
    // Answer options.
    /** @var array Valid answer options for multiple choice */
    const VALID_ANSWERS = ['A', 'B', 'C', 'D'];
    
    // Slide status constants.
    /** @var string Slide has been uploaded */
    const SLIDE_STATUS_UPLOADED = 'uploaded';
    
    /** @var string Slide processing is complete */
    const SLIDE_STATUS_COMPLETED = 'completed';
    
    /** @var string Slide processing encountered an error */
    const SLIDE_STATUS_ERROR = 'error';
    
    // Action constants.
    /** @var string Action to advance to next question */
    const ACTION_NEXT = 'next';
    
    /** @var string Action to stop session */
    const ACTION_STOP = 'stop';
    
    /** @var string Action to pause session */
    const ACTION_PAUSE = 'pause';
    
    /** @var string Action to resume session */
    const ACTION_RESUME = 'resume';
    
    /** @var array Valid control panel actions */
    const VALID_ACTIONS = [
        self::ACTION_NEXT,
        self::ACTION_STOP,
        self::ACTION_PAUSE,
        self::ACTION_RESUME,
    ];
    
    // Default configuration values.
    /** @var int Default polling interval in milliseconds */
    const DEFAULT_POLLING_INTERVAL = 1000;
    
    /** @var int Default number of questions per session */
    const DEFAULT_NUM_QUESTIONS = 10;
    
    /** @var int Default time limit per question in seconds */
    const DEFAULT_TIME_LIMIT = 30;
}
